[package]
name = "ldns-sys"
version = "0.1.0"
links = "ldns"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.59.2"
pkg-config = "0.3.25"
